;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="GamePlayCue.Notify.ScanEffect",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Test.Item.GlitchTrap",DevComment="")
+GameplayTagList=(Tag="GameplayCue.Test.Item.PickUp",DevComment="")

